[build]
builder = "railpack"

[start]
command = "uvicorn app:fastapi_app --host 0.0.0.0 --port 8000"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicy = "on-failure"
maxRetries = 10

[variables]
BOT_TOKEN = ""
WEBHOOK_BASE = "https://fun-production-8132.up.railway.app"
WEBHOOK_SECRET = "webhook-123"
ADMIN_CHAT_ID = "123456789"
GROUP_MONITOR_ID = "-1001748319682"
GROUP_PREMIUM_INVITE_LINK = "https://t.me/+HIzvM8sEgh1kNWY0"
